### ISSUE TITLE
Bilder

### ISSUE THREAD

**Issue by 22beer1bif** [hft-swp2-ws1516/website#14]
![bildschirmfoto vom 2015-12-07 22 20 54](https://cloud.githubusercontent.com/assets/15672743/11640258/ee436102-9d31-11e5-8e05-f17a22429cb7.png)

![bildschirmfoto vom 2015-12-07 22 31 36](https://cloud.githubusercontent.com/assets/15672743/11640368/7bb28c0c-9d32-11e5-80e0-264e740abdca.png)

![bildschirmfoto vom 2015-12-07 22 34 16](https://cloud.githubusercontent.com/assets/15672743/11640447/d1b88926-9d32-11e5-8259-3610b0663abd.png)

![bildschirmfoto vom 2015-12-07 22 37 54](https://cloud.githubusercontent.com/assets/15672743/11640543/5a54d460-9d33-11e5-8ce2-41bad7fc8207.png)

phpinfo()

![bildschirmfoto vom 2015-12-07 22 45 43](https://cloud.githubusercontent.com/assets/15672743/11640739/79b9cf58-9d34-11e5-9ffa-8c2365b1c5ae.png)

**Comment by ghost** [comment]
Hi Ermal, diese Bilder sehen super aus. Könntest du mir aber bitte kurz erklären, welcher Gedanke dem Slider zugrunde liegt?

**Comment by 22beer1bif** [comment]
Klar sehr gerne sogar. Also mein erster Gedanke war erstmal, dass der Save Button Safe ist weil er ja erst mittels toggle Button aktiviert wird. Also ne kleine Maßnahme wenn man das so sehen will. Mein zweiter Gedanke war dann sozusagen, dass der User damit einverstanden erklärt sich zu Subscriben. Sieh es vllt als ich akzeptiere die "AGBs". Und damit hoffe ich dir die Antwort gegeben zu haben.

**Comment by ghost** [comment]
Vielen Dank. An dieser Stelle aber eine kleine Anmerkung: Ich sehe gerade, dass der Benutzer, um überhaupt auf das "Subscribe"-Fenster zu kommen, ohnehin schon einen Link mit der Aufschrift "Subscribe" klicken muss - ich denke, wenn ein Benutzer erst das "Subscribe"-Fenster sieht, hat er damit doch recht deutlich gemacht, dass er daran interessiert ist, unsere Seite zu abonnieren. Eine zusätzliche Abfrage nach dem Motto "Lieber Benutzer, bist du dir sicher, dass du dir sicher bist?" wird damit aus meiner Sicht hinfällig - man stelle sich nur einmal das verwirrte Gesicht eines Benutzers vor, der gerade den Subscribe-Link geklickt und dann bereits seine E-Mail-Adresse angegeben hat, nur um dann abermals vor die Wahl gestellt zu werden, ob er eine Abonnierung wünscht oder nicht. Für den Fall, dass sich jemand im letzten Moment doch dagegen entscheidet, stehen außerdem ja immer noch der "Close"-Button und das unauffällige Kreuz oben rechts zur Verfügung.

**Comment by 22beer1bif** [comment]
Also ich finde es super, dass du dir da so richtig Gedanken gemacht hast wie ein User da dumm aus der Wäsche schauen könnte wenn er noch nen Hindernis überwinden müsse um sich für unsere tolle Seite zu Subscriben bzw. die Mail zu bekommen. Aber manche, ich gehöre der Kategorie User an, wären absolut nicht dadurch verwirrt wenn da noch ein toggle Button steht um dann endlich mich für die Erhaltung der Mail abonieren zu können. So und was das unauffällig Kreuz angeht sag ich es mal so: Das Kreuz mein lieber bzw. das komplette Modal und da ist die css miteinbegriffen, ist das Produkt von Bootstrap. Und bootstrap verwenden wir nunmal. Aber ich hätte nichts dagegen wenn du ein Modal mit einen auffälligen Kreuz implementieren würdest.

**Comment by benleb** [comment]
Morgen... seit wann diskutieren wir Issues denn auf deutsch?

Zum Thema... meine Ansicht nach is der Toggle auch überflüssig, ich klick subscribe - ich trag meine Mailadresse da ein - klick wieder subscribe, was gibts da noch zu bestätgigen mit nem Toggle?!

Viel wichtiger - gibts ne Validierung für die Mail-Adressen? Sonst kann irgendjemand da ja auch fremde Adressen eintragen... Das muss unbedingt wirksam verhindert werden!

Und, wenn du uns was zeigen willst - benutz Slack oder wegen mir auch noch GDrive. Issues sind nicht dafür gedacht und es "zerstört" die Burndown-Chart usw. wenn wir solche Issues hier aufmachen...
