### ISSUE TITLE
World Map with PFS distribution

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/website#17]
This is a requirement for the minimal version. 
There is already a issue for TLD specific in the db-api Repo open.

**Comment by ghost** [comment]
@22mege1bif: May I ask for a short status update? The world map functions are not working for me.

**Comment by 22mege1bif** [comment]
Its not working due to the name changing from http to https. Thats what i intend to do during this week it should work by changing it to https

**Comment by Lukas1Komarek** [comment]
No, its not working because there are no PFS data for January. I already tried to fix it with changing from http to https.

**Comment by ghost** [comment]
In view of the fact that the current month's data is never complete as long as the month itself has not passed, I suggest that we just take the data of the preceding month.

**Comment by ghost** [comment]
Given this case, it would be necessary to notify the user about what month is actually taken for evaluating the results.
