### ISSUE TITLE
Cipher Suites Graph + History (First Version)

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/website#3]
Don't know if there is a redundancy with Nico's Filter Functionality.

A Graph that supplies ordered information about the frequency of a all Ciphersuites. 

``` javascript
 var most_used_ciphersuites = [
    {"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256": 42},
    { "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384": 1337},
    {...}
];
```
## History

We need a history of how the frequency of a cipher suites changed in a given timespan. This will be displayed in a line diagram.

**Comment by Lukas1Komarek** [comment]
First version of Graph is ready. Please give Feedback to my commit.

**Comment by ghost** [comment]
Quite amazing, if you ask me! Is there really every cipher suite out there included?

**Comment by zirkler** [comment]
good job :+1:

**Comment by Lukas1Komarek** [comment]
I merged all ciphersuites from different tls versions, sorted by count and sliced the first 20 elements. But the high numbers are confusing, in fact we scanned about 600k hosts.
