### ISSUE TITLE
Filter: Include total number of matching cipher suites

### ISSUE THREAD

**Issue by ghost** [hft-swp2-ws1516/website#30]
As a user, I want to see the total number of cipher suites that match my selection displayed in a graph and not only the number for each protocol because in the latter case, it is hard to estimate the total amount of matching cipher suites in relation to the total amount of cipher suites available.

**Comment by Lukas1Komarek** [comment]
You could, let the user decide which TLS Version he wants to know. The Numbers are in relation with the total number of hosts per TLS Version.

**Comment by ghost** [comment]
What you are mentioning is already achievable by simply specifying the desired protocol before applying the filter. Maybe I wasn't clear enough there in the issue description, but displaying the total number of matches does only make sense if the components the number consists of are split in several bars of the graph which is exactly the case if no protocol was specified and the program displays the results for each protocol.

**Comment by ghost** [comment]
Implemented in 740fdfe.
