### ISSUE TITLE
Custom Error-Handling for Server Codes

### ISSUE THREAD

**Issue by 22beer1bif** [hft-swp2-ws1516/website#45]
We should have custom error-handling for "File not found example" and other important Server Codes.

**Comment by 22beer1bif** [comment]
Implemented Server Codes Error-Handling

**Comment by benleb** [comment]
Not working (661c9e1f50a10a11629364c8269da8ccbdf1090d), please fix and test before git push!

**Comment by 22beer1bif** [comment]
It works on my Server. As i mentioned it at .htaccess you should adjust the path and set the overide at /etc/apache2/Sites-availeble/000-default.conf on hotcat Server.

**Comment by benleb** [comment]
It should work on our server, not on yours...

**Comment by 22beer1bif** [comment]
there is no Problem in the Code it is probably a Server configuration Problem like the subscribtion functionality.
