### ISSUE TITLE
Subscribe does not work and probably never had...

### ISSUE THREAD

**Issue by benleb** [hft-swp2-ws1516/website#51]
`PHP Fatal error:  Class 'MongoClient' not found`

wtf? test your fucking code before pushing!

**Comment by 22beer1bif** [comment]
Wtf are you talking about? I've shown a full functional code yesterday on my presentation and I I always test it locally before I push to git.

**Comment by 22beer1bif** [comment]
Go to /etc/php5/cli/php.ini and add this:
extension=mongo.so
and probably if there are any needs for that:
extension_dir = "/usr/lib/php5/(2............)".
Last folder depends what you have installed. But it should be a folder named by numbers.
