### ISSUE TITLE
Worldmap coloring for countries that are avaiable.

### ISSUE THREAD

**Issue by KNiedziela** [hft-swp2-ws1516/website#55]
Is it possible? Adding into the line 111 in the worldmap.html file the attribute color (example: color: "#000000"),that is randomly generated for the countries that are "clickable". Example of color generator: ("#"+((1<<24)*Math.random()|0).toString(16)

**Comment by Lukas1Komarek** [comment]
Look at 801dcac24ea7b6961ee1aacf91c93a3d4aa2ebe7
