### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/website#8]
We named our Project "HOTCAT". Which stands for Hft Opensource Tool for Crawling the Advancements  of Tls. Now we  need a Logo, that has something to do with a cat.

**Comment by NicoAnt** [comment]
Logo is online in GoogleDrive now

**Comment by Lukas1Komarek** [comment]
.jpg or .gif .png file would be nice.

**Comment by NicoAnt** [comment]
png will comming soon! I saved it as pdf-file because it's a vector graphic. I thought it would make sence if we want to scale it for different things.

**Comment by NicoAnt** [comment]
.svg online
