### ISSUE TITLE
"Analyse me" feature

### ISSUE THREAD

**Issue by Lukas1Komarek** [hft-swp2-ws1516/website#9]
The analyse me feature is a own html page on the website. The user should be able to type in an URL and all information of our Crawler should be returned dynamically on the page. There are many things we could implement: e.g.  Problems, like using weak ciphers can be marked as red.

If the URL is already available in the alexa top 1m, then the data should be requested from the database. If not, the URL will be send to the message queue of the running scanner/cralwer, which have a higher priority than other URLs and if the scan has finished, the information will be returned via a webserver. 

Example: https://www.ssllabs.com/ssltest/

**Comment by Lukas1Komarek** [comment]
URL Syntax check is not working. The input field should accept all things like http://... https://..., www..., google.de. For more Information please contact the crawler team.

**Comment by Lukas1Komarek** [comment]
If the scanner is working you can get scan results for a specific Domain via POST request

```
curl --data "domain=google.com" hotcat.de:50002/analyzeme
```

**Comment by Lukas1Komarek** [comment]
Output sample: of facebook.de
https://gist.github.com/Lukas1Komarek/f42d0aeb1b4da3877b76

**Comment by ghost** [comment]
@NicoAnt, please give us a short update. What's the status of this issue? As of now, the "Analyse Me" feature does not seem to be working.
